### ISSUE TITLE
GET ERROR when install pljava on gp6.4

### ISSUE THREAD

**Issue by LittleWuCoding** [greenplum-db/pljava#44]
Hi，I am using GP6.4 on RHEL7 and wanna to use pljava 
So I download the code of branch tag 2.0.2 and branch gpdb6_release and try to compile with mvn
```
mvn clean install
```
according to README

I got ERROR when I install my compiled  pljava :
```
postgres=# create extension pljava;
ERROR:  query plan with multiple segworker groups is not supported
HINT:  likely caused by a function that reads or modifies data in a distributed table
```

And I also down the gppkg pljava-2.0.2-gp6-rhel7_x86_64.gppkg
this time I can successfully  install pljava.

That confusing me.
So, I compared the  compiled pljava and yours .gppkg package,
What confusing me is that:
(1) the content of  pljava.sql is total different between compiled source and the  gppkg
(2) Directory structure is also different

Is the gppkg  not compiled from this code on github? Or there is anything wrong in compile your code?

**Comment by jiarenfu** [comment]
@LittleWuCoding

**Comment by jiarenfu** [comment]
@LittleWuCoding  
Check the Java environment variables，jdk8 and jdk11 have different path
you can execute   psql -f  ${GPHOME}/share/postgresql/extension/pljava--1.5.0.sql
 Check which node has a problem
